---
- name: Create ec2 instances
  hosts: localhost
  tasks: 
    - name: launch the ec2 instances
      ec2: 
        key_name: "ansible"
        assign_public_ip: yes
        instance_type: "t2.micro"
        region: "eu-west-1"
        image: "ami-02a39bdb8e8ee056a"                              # ubuntu imag e"ami-0de7daa7385332688"
        vpc_subnet_id: "subnet-c0c8bd88"
        count: 1

