---
- name: install wordpress
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Install Webserver and dependencies
      package:
        name: "{{ item }}" 
      with_items:
        - httpd
        - elinks
        - php
        - php-gd
        - mysql
        - mariadb-server
        - php-mysql
      ignore_errors: yes

    - name: Get wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp


    - name: Unzip wordpress
      unarchive:
        src: /tmp/wordpress-5.1.tar.gz
        dest: /var/www/html
        remote_src: yes

